version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
    - "5432:5432"
    volumes:
    - chat-db:/var/lib/postgresql/data
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "5050:80"
    volumes:
    - chat-pgadmin-data:/var/lib/pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
 
volumes:
  chat-db:
  chat-pgadmin-data:

networks:
  postgres:
    driver: bridge
